language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - pip install openpyxl==2.0.3
    - pip install coverage==3.7.1
    - pip install pytest pytest-cov
    - pip install coveralls
install: 
    - pip install -r requirements.txt
    - pip install -r optional-packages.txt
script:
    - py.test --cov=lasio
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - kinverarity@hotmail.com
    on_success: change
    on_failure: always